WebsiteBanhang/WebBanHangOnline/Models/EF/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebBanHangOnline.Models.EF
{
    [Table("tb_Contact")]
    public class Contact : CommonAbstract
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(150,ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Name { get; set; }
        [StringLength(150, ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Email { get; set; }
        public string Website { get; set; }
        [StringLength(4000)]
        public string Message { get; set; }
        public bool IsRead { get; set; }
    }
}

WebsiteBanhang/WebBanHangOnline/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHangOnline.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Employee")]
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebsiteBanhang/WebBanHangOnline/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;

namespace WebBanHangOnline.Controllers
{
    public class ContactController : Controller
    {
      
        // GET: Contact
        public ActionResult Index(string id)
        {
            return View();
        }
    }
}

WebsiteBanhang/WebBanHangOnline/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
         
            //WebBanHangOnline.Common.Common.SendMail("ABC", "AAAA", "AAAA", "ngohoang29@gmail.com");
            return View();
        }
        

        public ActionResult Partial_Subcrice()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Subscribe(Subscribe req)
        {
            if (ModelState.IsValid)
            {
                db.Subscribes.Add(new Subscribe { Email = req.Email, CreatedDate = DateTime.Now });
                db.SaveChanges();
                return Json(new {Success=true });
            }
            return View("Partial_Subcrice", req);
        }
        public ActionResult About()
        {
           

            return View();
        }
        public ActionResult Refresh()
        {
            var item = new ThongKeModel();

            ViewBag.Visitors_online = HttpContext.Application["visitors_online"];
            var hn = HttpContext.Application["HomNay"];
            item.HomNay = HttpContext.Application["HomNay"].ToString();
            item.HomQua = HttpContext.Application["HomQua"].ToString();
            item.TuanNay = HttpContext.Application["TuanNay"].ToString();
            item.TuanTruoc = HttpContext.Application["TuanTruoc"].ToString();
            item.ThangNay = HttpContext.Application["ThangNay"].ToString();
            item.ThangTruoc = HttpContext.Application["ThangTruoc"].ToString();
            item.TatCa = HttpContext.Application["TatCa"].ToString();
            return PartialView(item);
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebsiteBanhang/WebBanHangOnline/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;

namespace WebBanHangOnline.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuTop()
        {
            var items = db.Categories.OrderBy(x=>x.Position).ToList();
            return PartialView("_MenuTop", items);
        }

        public ActionResult MenuProductCategory()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("_MenuProductCategory", items);
        }
        public ActionResult MenuLeft(int? id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.ProductCategories.ToList();
            return PartialView("_MenuLeft", items);
        }

        public ActionResult MenuArrivals()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("_MenuArrivals", items);
        }

    }
}

WebsiteBanhang/WebBanHangOnline/Controllers/NewsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: News
        public ActionResult Index(int? page)
        {
            var pageSize = 1;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<News> items = db.News.OrderByDescending(x=>x.CreatedDate);
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Detail(int id)
        {
            var item = db.News.Find(id);
            return View(item);
        }
        public ActionResult Partial_News_Home()
        {
            var items = db.News.Take(3).ToList();
            return PartialView(items);
        }
    }
}

WebsiteBanhang/WebBanHangOnline/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Products
        public ActionResult Index(int? page, string Searchtext)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1); // Default to page 1 if page is null

            IQueryable<Product> items = db.Products.OrderByDescending(x => x.Id);

            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }

            var pagedItems = items.ToList();

            return View(pagedItems);
        }


        public ActionResult Detail(string alias,int id)
        {
            var item = db.Products.Find(id);
            if (item != null)
            {
                db.Products.Attach(item);
                item.ViewCount = item.ViewCount + 1;
                db.Entry(item).Property(x => x.ViewCount).IsModified = true;
                db.SaveChanges();
            }
            var countReview = db.Reviews.Where(x => x.ProductId == id).Count();
            ViewBag.CountReview = countReview;
            return View(item);
        }
        public ActionResult ProductCategory(string alias,int id)
        {
            var items = db.Products.ToList();
            if (id > 0)
            {
                items = items.Where(x => x.ProductCategoryId == id).ToList();
            }
            var cate = db.ProductCategories.Find(id);
            if (cate != null)
            {
                ViewBag.CateName = cate.Title;
            }

            ViewBag.CateId = id;
            return View(items);
        }

        public ActionResult Partial_ItemsByCateId()
        {
            var items = db.Products.Where(x => x.IsHome && x.IsActive).Take(12).ToList();
            return PartialView(items);
        }

        public ActionResult Partial_ProductSales()
        {
            var items = db.Products.Where(x => x.IsSale && x.IsActive && x.PriceSale > 0 && x.IsHome).Take(12).ToList();
            return PartialView(items);
        }

      
    }
}

WebsiteBanhang/WebBanHangOnline/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/contact_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/contact_responsive.css">
<div class="container contact_container">
    <div class="row">
        <div class="col">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">
                <ul>
                    <li><a href="about.html">Giới thiệu</a></li>

                </ul>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2>Giới thiệu</h2>
            <p>
                Thương hiệu QLT (thuộc CTY TNHH Đầu Tư và Thương Mại Minh Gia Phú) mang đến một phong cách thời trang năng động, cá tính dành cho giới trẻ.
            </p>
            <p>
                Xuất hiện trên thị trường từ năm 2017 , hiện nay PAPKA đã có gần 100 gian hàng tại các hệ thống siêu thị EMART, AEON MALL, GO! BIGC, WINMART, CO.OPMART, CO.OPXTRA, SENSE CITY, LOTTE MART, MEGA MARTKET,....trải dài khắp cả nước... Những sản phẩm của PAPKA mang tính tiện ích cao, cơ bản và năng động, với các dòng sản phẩm thời trang Nam/Nữ như: Áo polo, Jeans Denim, Kaki cotton, T-shirt, Sơ mi, Đầm, Váy, Yếm…

            </p>
            <p>
                Tiêu chí của PAPKA luôn mong muốn đưa những sản phẩm của mình đến người tiêu dùng với những mẫu mã, chất liệu độc đáo, mới lạ được cập nhật thường xuyên với giá cả tốt nhất trong một không gian mua sắm thoải mái, sang trọng cùng với dịch vụ chăm sóc khách hàng hoàn hảo nhất.
            </p>
            <p>
                PAPKA mong muốn xây dựng một thương hiệu thời trang lớn mạnh trong nước phục vụ cho mọi độ tuổi và cá tính của người Việt.
            </p>
            <p>
                Mọi chi tiết xin vui lòng liên hệ Bộ Phận Chăm Sóc Khách Hàng:
            </p>
            <p>
                Hotline: 0344 002 108
            </p>
            <p>
                Email: tung2982004@gmail.com
            </p>
            <p>
                Website: www.qltshop.com
            </p>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/assets/js/contact_custom.js"></script>
}

WebsiteBanhang/WebBanHangOnline/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    176 Trần Xuân Lê<br />
    Thanh Khê, Đà Nẵng<br />
    <abbr title="Phone">Số điện thoại:</abbr>
    0344002108
</address>

<address>
    <strong>Bộ phận hỗ trợ:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Bộ phận marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebsiteBanhang/WebBanHangOnline/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Shop Online";
    ViewBag.SeoDescription = "Shop Online";
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
<!-- Slider -->

<div class="main_slider" style="background-image:url(Content/assets/images/main3.jpg)">
    <div class="container fill_height">
        <div class="row align-items-center fill_height">
            <div class="col">
                <div class="main_slider_content">
                    
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Banner -->
@Html.Action("MenuProductCategory", "Menu")

<!-- New Arrivals -->

<div class="new_arrivals">
    <div class="container">
        @Html.Action("MenuArrivals", "Menu")
    </div>
</div>

<!-- Deal of the week -->

<div class="deal_ofthe_week">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="deal_ofthe_week_img">
                    <img src="~/Content/assets/images/deal.png" alt="">
                </div>
            </div>
            <div class="col-lg-6 text-right deal_ofthe_week_col">
                <div class="deal_ofthe_week_content d-flex flex-column align-items-center float-right">
                    <div class="section_title">
                        <h2>Đếm ngược ngày giảm giá của tuần</h2>
                    </div>
                    <ul class="timer">
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="day" class="timer_num">03</div>
                            <div class="timer_unit">Ngày</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="hour" class="timer_num">15</div>
                            <div class="timer_unit">Giờ</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="minute" class="timer_num">45</div>
                            <div class="timer_unit">Phút</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="second" class="timer_num">23</div>
                            <div class="timer_unit">Giây</div>
                        </li>
                    </ul>
                    <div class="red_button deal_ofthe_week_button"><a href="/san-pham">Mua sắm ngay</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Best Sellers -->
@Html.Action("Partial_ProductSales", "Products")
<!-- Benefit -->

<div class="benefit">
    <div class="container">
        <div class="row benefit_row">
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-truck" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Miễn phí ship</h6>
                        <p>Hàng ngàn ưu đãi</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-money" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Giao hàng nhanh</h6>
                        <p>3-4 ngày</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-undo" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>45 ngày nữa</h6>
                        <p>Làm cho ngày mới thật bùng nổ</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Mở của xuyên suốt</h6>
                        <p>8AM - 9PM</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Blogs -->
@Html.Action("Partial_News_Home", "News")

WebsiteBanhang/WebBanHangOnline/Views/Home/Partial_Subcrice.cshtml
@model WebBanHangOnline.Models.EF.Subscribe

<div class="newsletter">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center">
                    <h4>Tin tức thời trang</h4>
                    <p>Đăng kí để nhận thông báo về tin tức thời trang mới nhất cũng như các ưu đãi</p>
                </div>
            </div>
            <div class="col-lg-6">
                @using (Ajax.BeginForm("Subscribe", "Home", new AjaxOptions
                {
                    OnBegin = "OnBeginSub",
                    OnSuccess = "OnSuccessSub",
                    OnFailure = "OnFailureSub"
                }))
                {
                    @Html.AntiForgeryToken()
                    <script>
                        function OnBeginSub() {

                        }
                        function OnSuccessSub (rs) {
                            if (rs.Success) {
                                alert("OK");
                            }
                        }
                        function OnFailureSub(rs) {}
                    </script>
                    <div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center">
                       @*@Html.TextBoxFor(x => x.Email, new {})*@
                        <input id="newsletter_email" name="Email" type="email" placeholder="Email của bạn" required="required" data-error="Valid email is required.">
                        <button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">Đăng kí</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

WebsiteBanhang/WebBanHangOnline/Views/Home/Refresh.cshtml
@model WebBanHangOnline.Models.ThongKeModel
@if (Model != null)
{
  <div class="thongke">
      <table class="table">
          <tr>
              <td>Hôm nay</td>
              <td>@Model.HomNay</td>
          </tr>
          <tr>
              <td>Hôm qua</td>
              <td>@Model.HomQua</td>
          </tr>
          <tr>
              <td>Tuần này</td>
              <td>@Model.TuanNay</td>
          </tr>
          <tr>
              <td>Số người Online</td>
              <td>@ViewBag.Visitors_online</td>
          </tr>
      </table>
  </div>
}